on: [push, pull_request, create, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Initialize workspace (west init)
        run: west init -l build/test
      - name: Update modules (west update)
        run: cd build/ && west update
      - name: Export Zephyr (west zephyr-export)
        run: cd build/ && west zephyr-export
      - name: West Build (xiao soloe)
        run: cd build/test && west build -s ../zmk/app -b seeeduino_xiao -- -DSHIELD=xiao_solo -DZEPHYR_MODULES=$(pwd)/../../
